=== 1099469599/Teaching/JavaEE Framework/XML/src/dtd/car.dtd
<!ELEMENT cars (car*)>
<!ELEMENT car (engine,wheels,seats)>
<!ATTLIST car id CDATA #REQUIRED>
<!ATTLIST car name CDATA #IMPLIED>
<!ELEMENT engine (brand,power)>
<!ELEMENT power (#PCDATA)>
<!ATTLIST engine id CDATA #REQUIRED>
<!ATTLIST engine type CDATA #FIXED "oil">
<!ELEMENT wheels (brand,count)>
<!ELEMENT seats (brand,kind,count)>
<!ELEMENT brand (#PCDATA)>
<!ELEMENT kind (#PCDATA)>
<!ELEMENT count (#PCDATA)>

=== 1099469599/Teaching/JavaEE Framework/XML/bin/dtd/car.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE car SYSTEM "car.dtd">
<cars>
	<car id="001" name="bmw x5">
		<engine id="xxxxxx" type="oil">
			<brand></brand>
			<power></power>
		</engine>
		<wheels>
			<brand></brand>
			<count></count>
		</wheels>
		<seats>
			<brand></brand>
			<kind></kind>
			<count></count>
		</seats>
	</car>
	<car id="002" name="benz s350">
		<engine id="xxxxxx">
			<brand></brand>
			<power></power>
		</engine>
		<wheels>
			<brand></brand>
			<count></count>
		</wheels>
		<seats>
			<brand></brand>
			<kind></kind>
			<count></count>
		</seats>
	</car>
</cars>
