<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE students [
	<!ELEMENT students (student*)>
	<!ELEMENT student (name, class)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT class (#PCDATA)>
	<!ENTITY className "15ç§‹">
]>
<students>
	<student>
		<name>aa</name>
		<class>&className;</class>
	</student>
	<student>
		<name>bb</name>
		<class>&className;</class>
	</student>
</students>